# Generated by Django 2.2 on 2020-12-18 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='admin_code', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='로트넘버', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='백신이름', max_length=20)),
                ('min_temp', models.FloatField(help_text='최저온도 ex) -20~-80 중 -80')),
                ('max_temp', models.FloatField(help_text='최고온도 ex) -20~-80 중 -20')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lot')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VaccineType')),
            ],
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_type', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], default=1)),
                ('timestamp', models.IntegerField()),
                ('temp', models.FloatField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Administrator')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lot')),
            ],
        ),
    ]
