# Generated by Django 2.2 on 2020-12-18 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TxHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx', models.TextField(blank=True)),
                ('logistics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Logistics')),
            ],
        ),
    ]
