# Generated by Django 2.2 on 2020-12-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201218_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='hashed_secret_key',
            field=models.TextField(blank=True),
        ),
    ]
