# Generated by Django 2.2 on 2020-12-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_administrator_hashed_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='_from',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logistics',
            name='_to',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
