# Generated by Django 2.2 on 2020-12-19 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201218_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='vaccine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.VaccineType'),
        ),
    ]
