# Generated by Django 2.2 on 2020-12-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_logistics_vaccine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txhash',
            name='tx',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
